:heavy_plus_sign: Adding required dependency: php version
ArielMejiaDev/larapex-charts pull request #10
Opened 2020-12-17 14:13 UTC by ordago

Added the php version required to the composer file. The code used doesn't work below php7. 

More specifically scalar type hints. See here:

https://3v4l.org/Mp7GNj

2021-03-16 05:55 UTC, xx1196 commented
Buen detalle

2021-03-19 12:42 UTC, MarioPerini requested changes
With your change it does'nt work with php 8.0
do you agree with ">=7.0" ?

2021-03-19 13:35 UTC, ordago commented
@MarioPerini If I'm not mistaken that would mean saying it's compatible with php 9 (which doesn't exist so we don't know). It's usually recommended to be explicit.

````
        "php": "^7.0|^8.0",
```

2021-06-01 15:15 UTC, ArielMejiaDev requested changes

2021-06-01 15:15 UTC, ArielMejiaDev commented on composer.json
> +      "ext-json": "*",
Please add this change to make it useful for php 7 and 8:

```php
"php": "^7.0|^8.0",
```

2021-08-20 19:10 UTC, ArielMejiaDev commented
it has already been added in the new 2.0 version of the package it supports PHP 7.4 to PHP 8.0 at this moment, when new PHP version `8.1` begin to be popular I will add support for this.

Thanks for this suggestion and the PR 👍

2021-08-20 19:10 UTC, closed without merging